
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80684I78700K',
          '64-bit',
          'LGA1151',
          '3.7GHz',
          '4.7GHz',
          '6',
          '6 x 32KB Instruction 6 x 32KB Data',
          '6 x 256KB',
          '1 x 12MB',
          '14 nm',
          '95 Watts',
          'No',
          'Yes: Hyper-Threading',
          '64GB',
          'Intel UHD Graphics 630'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'YD2600BBAFBOX',
          '64-bit',
          'AM4',
          '3.4GHz',
          '3.9GHz',
          '6',
          '6 x 64KB Instruction 6 x 32KB Data',
          '6 x 512KB',
          '1 x 16.0MB',
          '12 nm',
          '65 Watts',
          'Yes',
          'Yes',
          '64GB',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80684I58600K',
          '64-bit',
          'LGA1151',
          '3.6GHz',
          '4.3GHz',
          '6',
          '6 x 32KB Instruction 6 x 32KB Data',
          '6 x 256KB',
          '1 x 9MB',
          '14 nm',
          '95 Watts',
          'No',
          'No',
          '64GB',
          'Intel UHD Graphics 630'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'YD270XBGAFBOX',
          '64-bit',
          'AM4',
          '3.7GHz',
          '4.3GHz',
          '8',
          '8 x 64KB Instruction 8 x 32KB Data',
          '8 x 512KB',
          '1 x 16.0MB',
          '12 nm',
          '105 Watts',
          'Yes',
          'Yes',
          '64GB',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80684I58400',
          '64-bit',
          'LGA1151',
          '2.8GHz',
          '4GHz',
          '6',
          '6 x 32KB Instruction 6 x 32KB Data',
          '6 x 256KB',
          '1 x 9MB',
          '14 nm',
          '65 Watts',
          'Yes',
          'No',
          '64GB',
          'Intel UHD Graphics 630'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'YD1600BBAEBOX',
          '64-bit',
          'AM4',
          '3.2GHz',
          '3.6GHz',
          '6',
          '6 x 64KB Instruction 6 x 32KB Data',
          '6 x 512KB',
          '2 x 8MB',
          '14 nm',
          '65 Watts',
          'Yes',
          'Yes',
          'No',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'YD2200C5FBBOX',
          '64-bit',
          'AM4',
          '3.5GHz',
          '3.7GHz',
          '4',
          '4 x 64KB Instruction 4 x 32KB Data',
          '4 x 512KB',
          '1 x 4MB',
          '14 nm',
          '65 Watts',
          'Yes',
          'No',
          'Radeon Vega 8',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80684I38100',
          '64-bit',
          'LGA1151',
          '3.6GHz',
          '4',
          '4 x 32KB Instruction',
          'L2 CACHE 4 x 256KB',
          '1 x 6MB',
          '14 nm',
          '65 Watts',
          'Yes',
          'No',
          '64GB',
          'Intel UHD Graphics 630',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'YD260XBCAFBOX',
          '64-bit',
          'AM4',
          '3.6GHz',
          '4.2GHz',
          '6',
          '6 x 64KB Instruction 6 x 32KB Data',
          '6 x 512KB',
          '1 x 16.0MB',
          '12 nm',
          '95 Watts',
          'Yes',
          'Yes',
          '64GB',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'YD2400C5FBBOX',
          '64-bit',
          'AM4',
          '3.6GHz',
          '3.9GHz',
          '4',
          '4 x 64KB Instruction 4 x 32KB Data',
          '4 x 512KB',
          '1 x 4MB',
          '14 nm',
          '65 Watts',
          'Yes',
          'Yes',
          'Radeon Vega 11',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80677I77700K',
          '64-bit',
          'LGA1151',
          '4.2GHz',
          '4.5GHz',
          '4',
          '4 x 32KB Instruction 4 x 32KB Data',
          '4 x 256KB',
          '1 x 8MB',
          '14 nm',
          '91 Watts',
          'No',
          'Yes: Hyper-Threading',
          '64GB',
          'Intel HD Graphics 630'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80684I78700',
          '64-bit',
          'LGA1151',
          '3.2GHz',
          '4.6GHz',
          '6',
          '6 x 32KB Instruction 6 x 32KB Data',
          '6 x 256KB',
          '1 x 12MB',
          '14 nm',
          '65 Watts',
          'Yes',
          'Yes: Hyper-Threading',
          '64GB',
          'Intel UHD Graphics 630'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'YD1200BBAEBOX',
          '64-bit',
          'AM4',
          '3.1GHz',
          '3.4GHz',
          '4',
          '4 x 64KB Instruction 4 x 32KB Data',
          '4 x 512KB',
          '1 x 8MB',
          '14 nm',
          '65 Watts',
          'Yes',
          'No',
          'No',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'YD1700BBAEBOX',
          '64-bit',
          'AM4',
          '3GHz',
          '3.7GHz',
          '8',
          '8 x 64KB Instruction 8 x 32KB Data',
          '8 x 512KB',
          '2 x 8MB',
          '14 nm',
          '65 Watts',
          'Yes',
          'Yes',
          'No',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80684I78086K',
          '64-bit',
          'LGA1151',
          '4GHz',
          '5GHz',
          '6',
          '6 x 32KB Instruction 6 x 32KB Data',
          '6 x 256KB',
          '1 x 12MB',
          '14 nm',
          '95 Watts',
          'No',
          'Yes: Hyper-Threading',
          '64GB',
          'Intel UHD Graphics 630'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'YD180XBCAEWOF',
          '64-bit',
          'AM4',
          '3.6GHz',
          '4GHz',
          '8',
          '8 x 64KB Instruction 8 x 32KB Data',
          '8 x 512KB',
          '2 x 8MB',
          '14 nm',
          '95 Watts',
          'No',
          'Yes',
          'No',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80677G4560',
          '64-bit',
          'LGA1151',
          '3.5GHz',
          '2',
          '2 x 32KB Instruction',
          'L2 CACHE 2 x 256KB',
          '1 x 3MB',
          '14 nm',
          '54 Watts',
          'Yes',
          'Yes: Hyper-Threading',
          '64GB',
          'Intel HD Graphics 610',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'YD195XA8AEWOF',
          '64-bit',
          'TR4',
          '3.4GHz',
          '4GHz',
          '16',
          '16 x 64KB Instruction 16 x 32KB Data',
          '16 x 512KB',
          '1 x 32MB',
          '14 nm',
          '180 Watts',
          'No',
          'Yes',
          '1TB',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i7-6700K',
          'BX80662I76700K',
          '64-bit',
          'LGA1151',
          '4GHz',
          '4.2GHz',
          '4 L1 CACHE',
          '4 x 32KB Data',
          '4 x 256KB',
          '1 x 8MB',
          '14 nm',
          '91 Watts',
          'No',
          'Yes: Hyper-Threading',
          '64GB'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Intel Core i5-8600 Coffee Lake 6-Core 3.1 GHz (4.3 GHz Turbo) LGA 1151 (300 Series) 65W BX80684I58600 Desktop Processor Intel UHD Graphics 630',
          'BX80684I58600',
          '64-bit',
          'LGA1151',
          '3.1GHz',
          '4.3GHz',
          '6 L1 CACHE',
          '6 x 32KB Data',
          '6 x 256KB',
          '1 x 9MB',
          '14 nm',
          '65 Watts',
          'Yes',
          'No',
          '64GB'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80677I57600K',
          '64-bit',
          'LGA1151',
          '3.8GHz',
          '4.2GHz',
          '4',
          '4 x 32KB Instruction 4 x 32KB Data',
          '4 x 256KB',
          '1 x 6MB',
          '14 nm',
          '91 Watts',
          'No',
          'No',
          '64GB',
          'Intel HD Graphics 630'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'YD2700BBAFBOX',
          '64-bit',
          'AM4',
          '3.2GHz',
          '4.1GHz',
          '8',
          '8 x 64KB Instruction 8 x 32KB Data',
          '8 x 512KB',
          '1 x 16.0MB',
          '12 nm',
          '65 Watts',
          'Yes',
          'Yes',
          '64GB',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'FX-8350',
          'FD8350FRHKBOX',
          '64-bit',
          'AM3+',
          '4GHz',
          '8',
          '4 x 64KB Instruction 8 x 16KB Data',
          '4 x 2MB',
          '1 x 8MB',
          '32 nm',
          '125 Watts',
          'Yes',
          'No',
          'No',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'YD160XBCAEWOF',
          '64-bit',
          'AM4',
          '3.6GHz',
          '4GHz',
          '6',
          '6 x 64KB Instruction 6 x 32KB Data',
          '6 x 512KB',
          '2 x 8MB',
          '14 nm',
          '95 Watts',
          'No',
          'Yes',
          'No',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80673I97980X',
          '64-bit',
          'LGA2066',
          '2.6GHz',
          '4.4GHz',
          '18',
          '18 x 32KB Instruction 18 x 32KB Data',
          '18 x 1MB',
          '1 x 24MB',
          '14 nm',
          '165 Watts',
          'No',
          'Yes: Hyper-Threading',
          '128GB',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'YD150XBBAEBOX',
          '64-bit',
          'AM4',
          '3.5GHz',
          '3.7GHz',
          '4',
          '4 x 64KB Instruction 4 x 32KB Data',
          '4 x 512KB',
          '2 x 8MB',
          '14 nm',
          '65 Watts',
          'Yes',
          'Yes',
          'No',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80684I38350K',
          '64-bit',
          'LGA1151',
          '4GHz',
          '4',
          '64 x 32KB Instruction',
          'L2 CACHE 64 x 256KB',
          '1 x 8MB',
          '14 nm',
          '91 Watts',
          'No',
          'No',
          '64GB',
          'Intel UHD Graphics 630',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Pentium Gold G5400',
          'BX80684G5400',
          '64-bit',
          'LGA1151',
          '3.7GHz',
          '2',
          '2 x 32KB Instruction 2 x 32KB Data',
          '2 x 256KB',
          '1 x 4MB',
          '14 nm',
          '58 Watts',
          'Yes',
          'Yes: Hyper-Threading',
          '64GB',
          'Intel UHD Graphics 610'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'YD170XBCAEWOF',
          '64-bit',
          'AM4',
          '3.4GHz',
          '3.8GHz',
          '8',
          '8 x 64KB Instruction 8 x 32KB Data',
          '8 x 512KB',
          '2 x 8MB',
          '14 nm',
          '95 Watts',
          'No',
          'Yes',
          'No',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i5-6600K',
          'BX80662I56600K',
          '64-bit',
          'LGA1151',
          '3.5GHz',
          '3.9GHz',
          '4 L1 CACHE',
          '4 x 32KB Data',
          '4 x 256KB',
          '1 x 6MB',
          '14 nm',
          '91 Watts',
          'No',
          'No',
          'Intel HD Graphics 530'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'YD130XBBAEBOX',
          '64-bit',
          'AM4',
          '3.5GHz',
          '3.7GHz',
          '4',
          '4 x 64KB Instruction 4 x 32KB Data',
          '4 x 512KB',
          '1 x 8MB',
          '14 nm',
          '65 Watts',
          'Yes',
          'No',
          'No',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80673I97900X',
          '64-bit',
          'LGA2066',
          '3.3GHz',
          '4.5GHz',
          '10',
          '10 x 32KB Instruction 10 x 32KB Data',
          '10 x 1MB',
          '1 x 13.75MB',
          '14 nm',
          '140 Watts',
          'No',
          'Yes: Hyper-Threading',
          '128GB',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'YD299XAZAFWOF',
          '64-bit',
          'TR4',
          '3GHz',
          '4.2GHz',
          '32',
          '32 x 64KB Instruction 32 x 32KB Data',
          '32 x 512KB',
          '8 x 8MB',
          '12 nm',
          '250 Watts',
          'No',
          'Yes',
          '1TB',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'FX-6300',
          'FD6300WMHKBOX',
          '64-bit',
          'AM3+',
          '3.5GHz',
          '6',
          '3 x 64KB Instruction 6 x 16KB Data',
          '3 x 2MB',
          '1 x 8MB',
          '32 nm',
          '95 Watts',
          'Yes',
          'No',
          'No',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80677I57400',
          '64-bit',
          'LGA1151',
          '3GHz',
          '3.5GHz',
          '4',
          '4 x 32KB Instruction 4 x 32KB Data',
          '4 x 256KB',
          '1 x 6MB',
          '14 nm',
          '65 Watts',
          'Yes',
          'No',
          '64GB',
          'Intel HD Graphics 630'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'YD1400BBAEBOX',
          '64-bit',
          'AM4',
          '3.2GHz',
          '3.4GHz',
          '4',
          '4 x 64KB Instruction 4 x 32KB Data',
          '4 x 512KB',
          '1 x 8MB',
          '14 nm',
          '65 Watts',
          'Yes',
          'Yes',
          'No',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80673I77820X',
          '64-bit',
          'LGA2066',
          '3.6GHz',
          '4.5GHz',
          '8',
          '8 x 32KB Instruction 8 x 32KB Data',
          '8 x 1MB',
          '1 x 11MB',
          '14 nm',
          '140 Watts',
          'No',
          'Yes: Hyper-Threading',
          '128GB',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80684I58500',
          '64-bit',
          'LGA1151',
          '3GHz',
          '4.1GHz',
          '6',
          '6 x 32KB Instruction 6 x 32KB Data',
          '6 x 256KB',
          '1 x 9MB',
          '14 nm',
          '65 Watts',
          'Yes',
          'No',
          '64GB',
          'Intel UHD Graphics 630'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'YD192XA8AEWOF',
          '64-bit',
          'TR4',
          '3.5GHz',
          '4GHz',
          '12',
          '12 x 64KB Instruction 12 x 32KB Data',
          '12 x 512KB',
          '1 x 32MB',
          '14 nm',
          '180 Watts',
          'No',
          'Yes',
          '1TB',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80677I77700',
          '64-bit',
          'LGA1151',
          '3.6GHz',
          '4.2GHz',
          '4',
          '4 x 32KB Instruction 4 x 32KB Data',
          '4 x 256KB',
          '1 x 8MB',
          '14 nm',
          '65 Watts',
          'Yes',
          'Yes: Hyper-Threading',
          '64GB',
          'Intel HD Graphics 630'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80677I57500',
          '64-bit',
          'LGA1151',
          '3.4GHz',
          '3.8GHz',
          '4',
          '4 x 32KB Instruction 4 x 32KB Data',
          '4 x 256KB',
          '1 x 6MB',
          '14 nm',
          '65 Watts',
          'Yes',
          'No',
          '64GB',
          'Intel HD Graphics 630'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i7-4790K',
          'BX80646I74790K',
          '64-bit',
          'LGA1150',
          '4GHz',
          '4.4GHz',
          '4 L1 CACHE',
          '4 x 32KB Data',
          '4 x 256KB',
          '1 x 8MB',
          '22 nm',
          '88 Watts',
          'Yes',
          'Yes: Hyper-Threading',
          'Intel HD Graphics 4600'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'YD190XA8AEWOF',
          '64-bit',
          'TR4',
          '3.8GHz',
          '4GHz',
          '8',
          '8 x 64KB Instruction 8 x 32KB Data',
          '8 x 512KB',
          '1 x 16MB',
          '14 nm',
          '180 Watts',
          'No',
          'Yes',
          '1TB',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i3-6100',
          'BX80662I36100',
          '64-bit',
          'LGA1151',
          '3.7GHz',
          '2',
          '2 x 32KB Instruction 2 x 32KB Data',
          '2 x 256KB',
          '1 x 3MB',
          '14 nm',
          '51 Watts',
          'Yes',
          'Yes: Hyper-Threading',
          '64GB',
          'Intel HD Graphics 530'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Pentium G4400',
          'BX80662G4400',
          '64-bit',
          'LGA1151',
          '3.3GHz',
          '2',
          '2 x 32KB Instruction 2 x 32KB Data',
          '2 x 256KB',
          '1 x 3MB',
          '14 nm',
          '54 Watts',
          'Yes',
          'No',
          '64GB',
          'Intel HD Graphics 510'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Xeon E5-2697 V3',
          'CM8064401807100',
          '64-bit',
          'LGA2011-3',
          '2.6GHz',
          '3.6GHz',
          '14 L1 CACHE',
          '14 x 32KB Data',
          '14 x 256KB',
          '1 x 35MB',
          '22 nm',
          '145 Watts',
          'No',
          'Yes: Hyper-Threading',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i5-6500',
          'BX80662I56500',
          '64-bit',
          'LGA1151',
          '3.2GHz',
          '3.6GHz',
          '4 L1 CACHE',
          '4 x 32KB Data',
          '4 x 256KB',
          '1 x 6MB',
          '14 nm',
          '65 Watts',
          'Yes',
          'No',
          '64GB'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i5-2400',
          'BX80623I52400',
          '64-bit',
          'LGA1155',
          '3.1GHz',
          '4',
          '4 x 32KB Instruction 4 x 32KB Data',
          '2 x 256KB',
          '1 x 6MB',
          '32 nm',
          '95 Watts',
          'Yes',
          'No',
          'Intel HD Graphics 2000',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i5-4460',
          'BX80646I54460',
          '64-bit',
          'LGA1150',
          '3.2GHz',
          '3.4GHz',
          '4 L1 CACHE',
          '4 x 32KB Data',
          '4 x 256KB',
          '1 x 6MB',
          '22 nm',
          '84 Watts',
          'Yes',
          'No',
          'Intel HD Graphics 4600'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'CM8068403358220',
          '64-bit',
          'LGA1151',
          '3.7GHz',
          '4.7GHz',
          '6',
          '6 x 32KB Instruction 6 x 32KB Data',
          '6 x 256KB',
          '1 x 12MB',
          '14 nm',
          '95 Watts',
          'No',
          'Yes: Hyper-Threading',
          '64GB',
          'Intel UHD Graphics 630'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80677I37100',
          '64-bit',
          'LGA1151',
          '3.9GHz',
          '2',
          '2 x 32KB Instruction',
          'L2 CACHE 2 x 256KB',
          '1 x 3MB',
          '14 nm',
          '51 Watts',
          'Yes',
          'Yes: Hyper-Threading',
          '64GB',
          'Intel HD Graphics 630',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80677I77740X',
          '64-bit',
          'LGA2066',
          '4.3GHz',
          '4.5GHz',
          '4',
          '4 x 32KB Instruction 4 x 32KB Data',
          '4 x 256KB',
          '1 x 8MB',
          '14 nm',
          '112 Watts',
          'No',
          'Yes: Hyper-Threading',
          '64GB',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Xeon E5-2699 V4',
          'CM8066002022506',
          '64-bit',
          'LGA2011-3',
          '2.2GHz',
          '3.6GHz',
          '22 L1 CACHE',
          '22 x 32KB Data',
          '22 x 256KB',
          '1 x 55MB',
          '14 nm',
          '145 Watts',
          'No',
          'Yes: Hyper-Threading',
          '1.5TB'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'FX-9590',
          'FD9590FHHKWOF',
          '64-bit',
          'AM3+',
          '4.7GHz',
          '5GHz',
          '8 L1 CACHE',
          '8 x 16KB Data',
          '4 x 2MB',
          '1 x 8MB',
          '32 nm',
          '220 Watts',
          'No',
          'No',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i7-6700',
          'BX80662I76700',
          '64-bit',
          'LGA1151',
          '3.4GHz',
          '4GHz',
          '4 L1 CACHE',
          '4 x 32KB Data',
          '4 x 256KB',
          '1 x 8MB',
          '14 nm',
          '65 Watts',
          'Yes',
          'Yes: Hyper-Threading',
          '64GB'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i5-6400',
          'BX80662I56400',
          '64-bit',
          'LGA1151',
          '2.7GHz',
          '3.3GHz',
          '4 L1 CACHE',
          '4 x 32KB Data',
          '4 x 256KB',
          '1 x 6MB',
          '14 nm',
          '65 Watts',
          'Yes',
          'No',
          '64GB'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i5-4690K',
          'BX80646I54690K',
          '64-bit',
          'LGA1150',
          '3.5GHz',
          '3.9GHz',
          '4 L1 CACHE',
          '4 x 32KB Data',
          '4 x 256KB',
          '1 x 6MB',
          '22 nm',
          '88 Watts',
          'Yes',
          'No',
          'Intel HD Graphics 4600'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80677G3930',
          '64-bit',
          'LGA1151',
          '2.9GHz',
          '2',
          '2 x 32KB Instruction',
          'L2 CACHE 2 x 256KB',
          '1 x 2MB',
          '14 nm',
          '51 Watts',
          'Yes',
          'No',
          '64GB',
          'Intel HD Graphics 610',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'AD950XAGABBOX',
          '64-bit',
          'AM4',
          '3.5GHz',
          '3.8GHz',
          '4',
          '2 x 96KB Instruction 4 x 32KB Data',
          '2 x 1MB',
          'None',
          '28 nm',
          '65 Watts',
          'Yes',
          'No',
          'No',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'YD295XA8AFWOF',
          '64-bit',
          'TR4',
          '3.5GHz',
          '4.4GHz',
          '16',
          '16 x 64KB Instruction 16 x 32KB Data',
          '16 x 512KB',
          '4 x 8MB',
          '12 nm',
          '180 Watts',
          'No',
          'Yes',
          '1TB',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'A4-3300',
          'AD3300OJZ22GX',
          '64-bit',
          'FM1',
          '2.5GHz',
          '2',
          '2 x 64KB Instruction 2 x 64KB Data',
          '2 x 512KB',
          'None',
          '32 nm',
          '65 Watts',
          'No',
          'No',
          'Radeon HD 6410D',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80684I38300',
          '64-bit',
          'LGA1151',
          '3.7GHz',
          '4',
          '4 x 32KB Instruction',
          'L2 CACHE 4 x 256KB',
          '1 x 8MB',
          '14 nm',
          '62 Watts',
          'Yes',
          'No',
          '64GB',
          'Intel UHD Graphics 630',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80673I77800X',
          '64-bit',
          'LGA2066',
          '3.5GHz',
          '4GHz',
          '6',
          '6 x 32KB Instruction 6 x 32KB Data',
          '6 x 1MB',
          '1 x 8.25MB',
          '14 nm',
          '140 Watts',
          'No',
          'Yes: Hyper-Threading',
          '128GB',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Intel Pentium Gold G5500 Coffee Lake Dual-Core 3.8 GHz LGA 1151 (300 Series) 54W BX80684G5500 Desktop Processor Intel UHD Graphics 630',
          'BX80684G5500',
          '64-bit',
          'LGA1151',
          '3.8GHz',
          '2',
          '2 x 32KB Instruction 2 x 32KB Data',
          '2 x 256KB',
          '1 x 4MB',
          '14 nm',
          '54 Watts',
          'Yes',
          'Yes: Hyper-Threading',
          '64GB',
          'Intel UHD Graphics 630'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'Athlon X4 845',
          'AD845XACKASBX',
          '64-bit',
          'FM2+',
          '3.5GHz',
          '3.8GHz',
          '4 L1 CACHE',
          '4 x 32KB Data',
          '1 x 1MB',
          'None',
          '28 nm',
          '65 Watts',
          'Yes',
          'No',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core 2 Duo E7500',
          'BX80571E7500',
          '64-bit',
          'LGA775',
          '2.93GHz',
          '2',
          '2 x 32KB Instruction 2 x 32KB Data',
          '1 x 3MB',
          'None',
          '45 nm',
          '65 Watts',
          'Yes',
          'No',
          'No',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'CD8067303734902',
          '64-bit',
          'LGA2066',
          '2.6GHz',
          '4.4GHz',
          '18',
          '18 x 32KB Instruction 18 x 32KB Data',
          '18 x 1MB',
          '1 x 24MB',
          '14 nm',
          '165 Watts',
          'No',
          'Yes: Hyper-Threading',
          '128GB',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i5-3570K',
          'BX80637I53570K',
          'DATA WIDTH',
          'SOCKET',
          'OPERATING FREQUENCY',
          'CORES',
          'L1 CACHE 4 x 32KB Instruction',
          'L2 CACHE',
          'L3 CACHE',
          'LITHOGRAPHY',
          'THERMAL DESIGN POWER',
          'INCLUDES CPU COOLER',
          'SIMULTANEOUS MULTITHREADING',
          'INTEGRATED GRAPHICS',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i5-3470',
          'BX80637i53470',
          '64-bit',
          'LGA1155',
          '3.2GHz',
          '4',
          '4 x 32KB Instruction 4 x 32KB Data',
          '4 x 256KB',
          '1 x 6MB',
          '22 nm',
          '77 Watts',
          'Yes',
          'No',
          'Intel HD Graphics 2500',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i7-3770',
          'BX80637I73770',
          '64-bit',
          'LGA1155',
          '3.4GHz',
          '4',
          '4 x 32KB Instruction 4 x 32KB Data',
          '4 x 256KB',
          '1 x 8MB',
          '22 nm',
          '77 Watts',
          'Yes',
          'Yes: Hyper-Threading',
          'Intel HD Graphics 4000',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80673I97940X',
          '64-bit',
          'LGA2066',
          '3.1GHz',
          '4.4GHz',
          '14',
          '14 x 32KB Instruction 14 x 32KB Data',
          '1214 x 1MB',
          '1 x 19.25MB',
          '14 nm',
          '165 Watts',
          'No',
          'Yes: Hyper-Threading',
          '128GB',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80673I97920X',
          '64-bit',
          'LGA2066',
          '2.9GHz',
          '4.4GHz',
          '12',
          '12 x 32KB Instruction 12 x 32KB Data',
          '12 x 1MB',
          '1 x 16.5MB',
          '14 nm',
          '140 Watts',
          'No',
          'Yes: Hyper-Threading',
          '128GB',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Celeron G3900',
          'BX80662G3900',
          '64-bit',
          'LGA1151',
          '2.8GHz',
          '2',
          '2 x 32KB Instruction 2 x 32KB Data',
          '2 x 256KB',
          '1 x 2MB',
          '14 nm',
          '51 Watts',
          'Yes',
          'No',
          '64GB',
          'Intel HD Graphics 510'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'FX-4300',
          'FD4300WMHKBOX',
          '64-bit',
          'AM3+',
          '3.8GHz',
          '4',
          '2 x 64KB Instruction 4 x 16KB Data',
          '2 x 2MB',
          '1 x 4MB',
          '32 nm',
          '95 Watts',
          'Yes',
          'No',
          'No',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Xeon E5-2643 V2',
          'CM8063501287403',
          '64-bit',
          'LGA2011',
          '3.5GHz',
          '3.8GHz',
          '6 L1 CACHE',
          '6 x 32KB Data',
          '6 x 256KB',
          '1 x 25MB',
          '22 nm',
          '130 Watts',
          'No',
          'Yes: Hyper-Threading',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Intel Pentium Gold G5600 Coffee Lake Dual-Core 3.9 GHz LGA 1151 (300 Series) 54W BX80684G5600 Desktop Processor Intel UHD Graphics 630',
          'BX80684G5600',
          '64-bit',
          'LGA1151',
          '3.9GHz',
          '2',
          '2 x 32KB Instruction 2 x 32KB Data',
          '2 x 256KB',
          '1 x 4MB',
          '14 nm',
          '54 Watts',
          'Yes',
          'Yes: Hyper-Threading',
          '64GB',
          'Intel UHD Graphics 630'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i7-4770K',
          'BX80646I74770K',
          '64-bit',
          'LGA1150',
          '3.5GHz',
          '4',
          '4 x 32KB Instruction 4 x 32KB Data',
          '4 x 256KB',
          '1 x 8MB',
          '22 nm',
          '84 Watts',
          'Yes',
          'Yes: Hyper-Threading',
          'Intel HD Graphics 4600',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i7-2600',
          'BX80623I72600',
          '64-bit',
          'LGA1155',
          '3.4GHz',
          '4',
          '4 x 32KB Instruction 4 x 32KB Data',
          '4 x 256KB',
          '1 x 8MB',
          '32 nm',
          '95 Watts',
          'Yes',
          'Yes: Hyper-Threading',
          'Intel HD Graphics 2000',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'AD9600AGABBOX',
          '64-bit',
          'AM4',
          '3.1GHz',
          '3.4GHz',
          '4',
          '2 x 96KB Instruction 4 x 32KB Data',
          '2 x 1MB',
          'None',
          '28 nm',
          '65 Watts',
          'Yes',
          'No',
          'Radeon R7 (on-die)',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80677I57600',
          '64-bit',
          'LGA1151',
          '3.5GHz',
          '4.1GHz',
          '4',
          '4 x 32KB Instruction 4 x 32KB Data',
          '4 x 256KB',
          '1 x 6MB',
          '14 nm',
          '65 Watts',
          'Yes',
          'No',
          '64GB',
          'Intel HD Graphics 630'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'FX-8320',
          'FD8320FRHKBOX',
          '64-bit',
          'AM3+',
          '3.5GHz',
          '8',
          '4 x 64KB Instruction 8 x 16KB Data',
          '4 x 2MB',
          '1 x 8MB',
          '32 nm',
          '125 Watts',
          'Yes',
          'No',
          'No',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i7-4790',
          'BX80646I74790',
          '64-bit',
          'LGA1150',
          '3.6GHz',
          '4GHz',
          '4 L1 CACHE',
          '4 x 32KB Data',
          '4 x 256KB',
          '1 x 8MB',
          '22 nm',
          '84 Watts',
          'Yes',
          'Yes: Hyper-Threading',
          'Intel HD Graphics 4600'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'AD9500AGABBOX',
          '64-bit',
          'AM4',
          '3.5GHz',
          '3.8GHz',
          '2',
          '1 x 96KB Instruction 2 x 32KB Data',
          '1 x 1MB',
          'None',
          '28 nm',
          '65 Watts',
          'Yes',
          'No',
          'Radeon R5 (on die)',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core 2 Duo E8400',
          'EU80570PJ0806M',
          '64-bit',
          'LGA775',
          '3GHz',
          '2',
          '2 x 32KB Instruction 2 x 32KB Data',
          '1 x 6MB',
          'None',
          '45 nm',
          '65 Watts',
          'No',
          'No',
          'No',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'YD295XA8UGAAF',
          '64-bit',
          'TR4',
          '3.5GHz',
          '4.4GHz',
          '16',
          '16 x 64KB Instruction 16 x 32KB Data',
          '16 x 512KB',
          '4 x 8MB',
          '12 nm',
          '180 Watts',
          'No',
          'Yes',
          '1TB',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80677I57640X',
          '64-bit',
          'LGA2066',
          '4GHz',
          '4.2GHz',
          '4',
          '4 x 32KB Instruction 4 x 32KB Data',
          '4 x 256KB',
          '1 x 6MB',
          '14 nm',
          '112 Watts',
          'No',
          'No',
          '64GB',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Xeon E5-2699 V3',
          'CM8064401739300',
          '64-bit',
          'LGA2011-3',
          '2.3GHz',
          '3.6GHz',
          '18 L1 CACHE',
          '18 x 32KB Data',
          '18 x 256KB',
          '1 x 45MB',
          '22 nm',
          '145 Watts',
          'No',
          'Yes: Hyper-Threading',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i7-4770',
          'BX80646I74770',
          '64-bit',
          'LGA1150',
          '3.4GHz',
          '4',
          '4 x 32KB Instruction 4 x 32KB Data',
          '4 x 256KB',
          '1 x 8MB',
          '22 nm',
          '84 Watts',
          'Yes',
          'Yes: Hyper-Threading',
          'Intel HD Graphics 4600',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i7-3770K',
          'BX80637I73770K',
          '64-bit',
          'LGA1155',
          '3.5GHz',
          '4',
          '4 x 32KB Instruction 4 x 32KB Data',
          '4 x 256KB',
          '1 x 8MB',
          '22 nm',
          '77 Watts',
          'Yes',
          'Yes: Hyper-Threading',
          'Intel HD Graphics 4000',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'FD8350FRHKHBX Wraith',
          'FD8350FRHKHBX',
          '64-bit',
          'AM3+',
          '4GHz',
          '8',
          '4 x 64KB Instruction 8 x 16KB Data',
          '4 x 2MB',
          '1 x 8MB',
          '32 nm',
          '125 Watts',
          'Yes',
          'No',
          'No',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Intel Celeron G4900 Coffee Lake Dual-Core 3.1 GHz LGA 1151 (300 Series) 54W BX80684G4900 Desktop Processor Intel UHD Graphics 610',
          'BX80684G4900',
          '64-bit',
          'LGA1151',
          '3.1GHz',
          '2',
          '2 x 32KB Instruction 2 x 32KB Data',
          '2 x 256KB',
          '1 x 2MB',
          '14 nm',
          '65 Watts',
          'Yes',
          'No',
          '64GB',
          'Intel UHD Graphics 610'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80677G4600',
          '64-bit',
          'LGA1151',
          '3.6GHz',
          '2',
          '2 x 32KB Instruction',
          'L2 CACHE 2 x 256KB',
          '1 x 3MB',
          '14 nm',
          '51 Watts',
          'Yes',
          'Yes: Hyper-Threading',
          '64GB',
          'Intel HD Graphics 630',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i7-5820K',
          'BX80648I75820K',
          '64-bit',
          'LGA2011-3',
          '3.3GHz',
          '3.6GHz',
          '6 L1 CACHE',
          '6 x 32KB Data',
          '6 x 256KB',
          '1 x 15MB',
          '22 nm',
          '140 Watts',
          'No',
          'Yes: Hyper-Threading',
          '64GB'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i5-4670K',
          'BX80646I54670K',
          '64-bit',
          'LGA1150',
          '3.4GHz',
          '4',
          '4 x 32KB Instruction 4 x 32KB Data',
          '4 x 256KB',
          '1 x 6MB',
          '22 nm',
          '84 Watts',
          'Yes',
          'No',
          'Intel HD Graphics 4600',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i5-6600',
          'BX80662I56600',
          '64-bit',
          'LGA1151',
          '3.3GHz',
          '3.9GHz',
          '4 L1 CACHE',
          '4 x 32KB Data',
          '4 x 256KB',
          '1 x 6MB',
          '14 nm',
          '65 Watts',
          'Yes',
          'No',
          '64GB'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80673I97960X',
          '64-bit',
          'LGA2066',
          '2.8GHz',
          '4.4GHz',
          '16',
          '16 x 32KB Instruction 16 x 32KB Data',
          '16 x 1MB',
          '1 x 22MB',
          '14 nm',
          '165 Watts',
          'No',
          'Yes: Hyper-Threading',
          '128GB',
          'No'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i5-4590',
          'BX80646I54590',
          '64-bit',
          'LGA1150',
          '3.3GHz',
          '3.7GHz',
          '4 L1 CACHE',
          '4 x 32KB Data',
          '4 x 256KB',
          '1 x 6MB',
          '22 nm',
          '84 Watts',
          'Yes',
          'No',
          'Intel HD Graphics 4600'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'Core i5-2500K',
          'BX80623I52500K',
          '64-bit',
          'LGA1155',
          '3.3GHz',
          '4',
          '4 x 32KB Instruction 4 x 32KB Data',
          '2 x 256KB',
          '1 x 6MB',
          '32 nm',
          '95 Watts',
          'Yes',
          'No',
          'Intel HD Graphics 3000',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'AMD',
          'FX-8300',
          'FD8300WMHKBOX',
          '64-bit',
          'AM3+',
          '3.3GHz',
          '8',
          '4 x 64KB Instruction 8 x 16KB Data',
          '4 x 2MB',
          '1 x 8MB',
          '32 nm',
          '95 Watts',
          'Yes',
          'No',
          'No',
          'undefined'
        );
        INSERT INTO cpu (
        MANUFACTURER,
        PARTNUM,
        DATAWIDTH,
        SOCKET,
        OPERATING_FREQUENCY,
        MAX_TURBO,
        CORES,
        L1_CACHE,
        L2_CACHE,
        L3_CACHE,
        LITHOGRAPHY,
        THERMAL_DESIGN_POWER,
        INCLUDES_CPU_COOLER,
        MULTI_THREADING,
        MAX_MEM,
        INT_GRAPHICS
        )VALUES(
          'Intel',
          'BX80671I76800K',
          '64-bit',
          'LGA2011-3',
          '3.4GHz',
          '3.6GHz',
          '6',
          '6 x 32KB Instruction 6 x 32KB Data',
          '6 x 256KB',
          '1 x 15MB',
          '14 nm',
          '140 Watts',
          'No',
          'Yes: Hyper-Threading',
          'No',
          'undefined'
        );
        